// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHucGij7SLwm66HmBwJnH8K-EAFBm3Sv0',
    appId: '1:704067096279:web:659c8dc96b49851ee6ea92',
    messagingSenderId: '704067096279',
    projectId: 'first-pro-df331',
    authDomain: 'first-pro-df331.firebaseapp.com',
    storageBucket: 'first-pro-df331.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsbrXLm-mzNnV6oIkFRQk4LE5FMDm5YJ4',
    appId: '1:704067096279:android:6fb550a7dff9c8d2e6ea92',
    messagingSenderId: '704067096279',
    projectId: 'first-pro-df331',
    storageBucket: 'first-pro-df331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtMt3dfBgGoF7UFOXo8pERqB3xLrIMow0',
    appId: '1:704067096279:ios:a9774d565831ba9fe6ea92',
    messagingSenderId: '704067096279',
    projectId: 'first-pro-df331',
    storageBucket: 'first-pro-df331.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtMt3dfBgGoF7UFOXo8pERqB3xLrIMow0',
    appId: '1:704067096279:ios:a9774d565831ba9fe6ea92',
    messagingSenderId: '704067096279',
    projectId: 'first-pro-df331',
    storageBucket: 'first-pro-df331.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHucGij7SLwm66HmBwJnH8K-EAFBm3Sv0',
    appId: '1:704067096279:web:b66e90036e11efe2e6ea92',
    messagingSenderId: '704067096279',
    projectId: 'first-pro-df331',
    authDomain: 'first-pro-df331.firebaseapp.com',
    storageBucket: 'first-pro-df331.firebasestorage.app',
  );
}
